### PR TITLE
Add DMAPS TJ BS thesis topic

### PR DESCRIPTION
**Pull request by cbespin**
This PR adds a section about DMAPS which currently contains one thesis topic for charge calibration of TJ-Monopix1

### CODE REVIEW

**Comment by leloup314** [comment]
Why the new theme? I think the logo will not be visible anymore, unless we also add our custom layout  ;) Other then that looks nice! Can I merge?

**Comment by DavidLP** [comment]
good idea

**Comment by DavidLP** [comment]
we could update an send it to the students already

**Comment by cbespin** [comment]
This commit should not include any changes, I hope. It was added by Github when I was testing it as a personal project site. Can you cherry.pick in the worst case?

**Comment by cbespin** [comment]
Otherwise I am done with this, you can merge @leloup314

**Pull request merged**
